# Generated by Django 3.1.2 on 2020-10-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='error',
            field=models.CharField(default='sin error', max_length=20),
            preserve_default=False,
        ),
    ]
