# Generated by Django 3.1.2 on 2020-10-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_ciudad_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='error',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='ejemplo2',
            field=models.DateField(null=True),
        ),
    ]
