# Generated by Django 3.1.2 on 2020-10-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_auto_20201017_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia')], max_length=64),
        ),
    ]
