# Generated by Django 3.1.2 on 2020-10-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0004_auto_20201017_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='ejemplo2',
        ),
    ]
