# Generated by Django 3.1.2 on 2020-10-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0006_aeropuerto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('sillas', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destino', to='vuelos.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origen', to='vuelos.aeropuerto')),
            ],
        ),
    ]
