# Generated by Django 3.1.2 on 2020-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0007_vuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='bandera',
            field=models.FileField(blank=True, null=True, upload_to='banderas/'),
        ),
    ]
